// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'itemContainer': string;
  'itemImage': string;
  'itemTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
